- hosts: all
  tasks:
    - name: disable selinux
      selinux:
        state: disabled

    - name: stop and disable firewall
      systemd:
        name: firewalld
        state: stopped
        enabled: no
        daemon_reload: yes

    - name: enable ipv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        sysctl_set: yes
        reload: yes

    - name: Remove swapfile from /etc/fstab
      mount:
        name: swap
        fstype: swap
        state: absent

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Install gluster-fuse
      yum: 
        name: gluster-fs
        state: latest

    - modprobe:
        name: dm_snapshot
        state: present

    - modprobe:
        name: dm_mirror
        state: present

    - modprobe:
        name: dm_thin_pool
        state: present
