- hosts: all
  tasks:
    - name: install epel
      yum:
        name: epel-release
        state: latest

    - name: download docker ce repo file
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: change to UESTC mirror site
      shell: sed -i "s#download.docker.com#mirrors.ustc.edu.cn/docker-ce#g" "{{ item }}"
      with_items:
        - /etc/yum.repos.d/docker-ce.repo

    - name: install docker
      yum:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - docker-ce

    - name: enable docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: disable selinux
      selinux:
        state: disabled

    - name: stop and disable firewall
      systemd:
        name: firewalld
        state: stopped
        enabled: no
        daemon_reload: yes

    - name: enable ipv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        sysctl_set: yes
        reload: yes

    - name: Remove swapfile from /etc/fstab
      mount:
        name: swap
        fstype: swap
        state: absent

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Install glusterfs-fuse
      yum: 
        name: glusterfs-fuse
        state: latest

    - modprobe:
        name: dm_snapshot
        state: present

    - modprobe:
        name: dm_mirror
        state: present

    - modprobe:
        name: dm_thin_pool
        state: present

    - name: copy docker images to remote hosts
      copy:
        src: ./docker-images/
        dest: /root/docker-images
        owner: root
        group: root
        mode: 0644

    - name: load docker images
      shell: find /root/docker-images/ -name "*.tar" -exec docker load -i {} \;
